config/routes.rb
Rails.application.routes.draw do
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def show
    @task = Task.find(params[:id])
  end
  def index
    @tasks = Task.all
  end
  def new
    @task = Task.new
  end
  def create
    @task = Task.new(task_params)
  @task.save
  redirect_to @task
  end
  def edit
    @task = Task.find(params[:id])
  end
  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to(@task)
  end
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end
private
  def task_params
    params.require(:task).permit(:title, :body, :due_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MofulloSelf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>タスク登録フォーム</h1>
<%= form_with model: @task, local: true do |form| %>
<p>タイトル：</p>
<%= form.text_field :title %>
<p>本文：</p>
<%= form.text_area :body %>
<p>期限：</p>
<%= form.date_field :due_date %>
<br>
<%= form.submit "更新"%>
<% end %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<ul>
  <% @tasks.each do |task| %>
  <li><%= link_to task.title, task %></li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>タスク登録フォーム</h1>
<%= form_with model: @task, local: true do |form| %>
<p>タイトル：</p>
<%= form.text_field :title %>
<p>本文：</p>
<%= form.text_area :body %>
<p>期限：</p>
<%= form.date_field :due_date %>
<br>
<%= form.submit "登録" %>
<br>
<%= link_to "一覧へ戻る", tasks_path %>
<% end %>

app/views/tasks/show.html.erb
<h1>タスク詳細</h1>
<p>【タイトル】</p>
<%= @task.title %>
<p>【本文】</p>
<%= @task.body %>
<p>【期限】</p>
<%= @task.due_date %>
<br>
<%= link_to "戻る", tasks_path %>
<%= link_to "編集", edit_task_path(@task) %>
<%= link_to "削除", task_path(@task), method: :delete, data: {confirm: '削除してよろしいですか？'} %>